ALTER TABLE public.agentes 
ADD COLUMN IF NOT EXISTS webhook_principal TEXT,
ADD COLUMN IF NOT EXISTS webhook_indexacao TEXT,
ADD COLUMN IF NOT EXISTS webhook_teste TEXT,
ADD COLUMN IF NOT EXISTS rag_threshold NUMERIC DEFAULT 0.7,
ADD COLUMN IF NOT EXISTS rag_resultados INTEGER DEFAULT 5,
ADD COLUMN IF NOT EXISTS rag_ativo BOOLEAN DEFAULT TRUE;